github: [bluedev-in]
# patreon: your_patreon_username
# open_collective: your_opencollective_username
# ko_fi: your_kofi_username
# tidelift: npm/package-name
# community_bridge: your_community_bridge_project_name
# liberapay: your_liberapay_username
# issuehunt: your_issuehunt_username
# ocrp: your_ocrp_username
# custom: ["https://www.paypal.me/your_paypal"]
